name: CompatHelper

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - actions/trigger/CompatHelper
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add(name="CompatHelper", version="1")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.SSH_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
